import type { Metadata } from "next";
import localFont from "next/font/local";
import {
  Bodoni_Moda,
  Caveat,
  Cinzel,
  Geist,
  Geist_Mono,
  Playfair_Display,
} from "next/font/google";
import "./globals.css";
import { LenisProvider } from "../components/LenisProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const serif = Playfair_Display({
  variable: "--font-serif",
  subsets: ["latin"],
});

const handwritten = Caveat({
  variable: "--font-handwritten",
  subsets: ["latin"],
});

const bodoni = Bodoni_Moda({
  variable: "--font-bodoni",
  subsets: ["latin"],
});

// Trajan-style Roman square capitals; used for monumental titles like
// "LEGERE" in the recommendation dossier.
const trajan = Cinzel({
  variable: "--font-trajan",
  subsets: ["latin"],
  weight: ["700", "900"],
});

const betterSaturday = localFont({
  src: "../public/fonts/BetterSaturday.ttf",
  variable: "--font-better-saturday",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${serif.variable} ${handwritten.variable} ${bodoni.variable} ${trajan.variable} ${betterSaturday.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col grainy-paper">
        <LenisProvider>{children}</LenisProvider>
      </body>
    </html>
  );
}
